"""empty message

Revision ID: 19ff3ff78b87
Revises: f823b980e26d
Create Date: 2016-10-20 12:54:33.576207

"""

# revision identifiers, used by Alembic.
revision = '19ff3ff78b87'
down_revision = 'f823b980e26d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('match_vip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_vip_id'], ['match_vip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    ### end Alembic commands ###
