"""Steam Login

Revision ID: 2ecce726994c
Revises: None
Create Date: 2016-10-11 09:19:54.807204

"""

# revision identifiers, used by Alembic.
revision = '2ecce726994c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
