""" 8/ Add mode and selection votes.

Revision ID: 55b56ebe06b2
Revises: d48c82d3c454
Create Date: 2017-01-03 15:42:01.978852

"""

# revision identifiers, used by Alembic.
revision = '55b56ebe06b2'
down_revision = 'd48c82d3c454'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queued_player', sa.Column('mode_vote', sa.Integer(), server_default='0', nullable=False))
    op.add_column('queued_player', sa.Column('selection_vote', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queued_player', 'selection_vote')
    op.drop_column('queued_player', 'mode_vote')
    # ### end Alembic commands ###
