"""10/ Update models for season 2

Revision ID: 739567e2c9cd
Revises: 38e5bbc1cd8f
Create Date: 2017-01-31 11:39:42.852981

"""

# revision identifiers, used by Alembic.
revision = '739567e2c9cd'
down_revision = '38e5bbc1cd8f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_in_match', sa.Column('mmr', sa.Integer(), nullable=False, default='0', server_default='0'))
    op.drop_column('player_in_match', 'mmr_after')
    op.drop_column('player_in_match', 'mmr_before')
    op.add_column('scoreboard', sa.Column('points', sa.Integer(), nullable=False, default='0', server_default='0'))
    op.create_index(op.f('ix_scoreboard_points'), 'scoreboard', ['points'], unique=False)
    op.drop_index('ix_scoreboard_mmr', table_name='scoreboard')
    op.drop_column('scoreboard', 'mmr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scoreboard', sa.Column('mmr', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_scoreboard_mmr', 'scoreboard', ['mmr'], unique=False)
    op.drop_index(op.f('ix_scoreboard_points'), table_name='scoreboard')
    op.drop_column('scoreboard', 'points')
    op.add_column('player_in_match', sa.Column('mmr_before', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('player_in_match', sa.Column('mmr_after', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('player_in_match', 'mmr')
    # ### end Alembic commands ###
