"""Initial database

Revision ID: a21be10cedb1
Revises: None
Create Date: 2016-10-13 18:54:26.047975

"""

# revision identifiers, used by Alembic.
revision = 'a21be10cedb1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_vip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_vip_created'), 'match_vip', ['created'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('basic_rights', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=False)
    op.create_table('queue_vip',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_vip_added'), 'queue_vip', ['added'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_vip_added'), table_name='queue_vip')
    op.drop_table('queue_vip')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_match_vip_created'), table_name='match_vip')
    op.drop_table('match_vip')
    ### end Alembic commands ###
