"""Initial Revision with very simple user.

Revision ID: bc0818bde404
Revises: None
Create Date: 2016-10-05 14:30:11.416621

"""

# revision identifiers, used by Alembic.
revision = 'bc0818bde404'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
