"""2/ Add a team slot to check if the user is in the good slot.

Revision ID: d2788e6855d8
Revises: f9ebfb0b8e3d
Create Date: 2016-11-23 15:27:42.419523

"""

# revision identifiers, used by Alembic.
revision = 'd2788e6855d8'
down_revision = 'f9ebfb0b8e3d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_in_match', sa.Column('team_slot', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_in_match', 'team_slot')
    ### end Alembic commands ###
