"""Add Mix infos and modify scan technique.

Revision ID: da31f53317e6
Revises: 25a05a77a62f
Create Date: 2016-11-08 12:23:31.809612

"""

# revision identifiers, used by Alembic.
revision = 'da31f53317e6'
down_revision = '25a05a77a62f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_scan_info',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('last_scan_request', sa.DateTime(), nullable=True),
    sa.Column('last_scan', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_mix_details',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_date', sa.DateTime(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mix_details_refresh_date'), 'user_mix_details', ['refresh_date'], unique=False)
    op.drop_column('user', 'last_scan')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_scan', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_mix_details_refresh_date'), table_name='user_mix_details')
    op.drop_table('user_mix_details')
    op.drop_table('profile_scan_info')
    ### end Alembic commands ###
