"""4/ Add server to spectate.

Revision ID: db21e76e6868
Revises: 5204ca453334
Create Date: 2016-11-25 17:56:30.563623

"""

# revision identifiers, used by Alembic.
revision = 'db21e76e6868'
down_revision = '5204ca453334'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('server', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'server')
    ### end Alembic commands ###
