"""empty message

Revision ID: dfd9f38bf4c7
Revises: 251c3d759b34
Create Date: 2016-10-25 10:49:02.673980

"""

# revision identifiers, used by Alembic.
revision = 'dfd9f38bf4c7'
down_revision = '251c3d759b34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mmr_checker',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mmr_checker_status'), 'mmr_checker', ['status'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mmr_checker_status'), table_name='mmr_checker')
    op.drop_table('mmr_checker')
    ### end Alembic commands ###
