"""1/ Initial Database

Revision ID: f9ebfb0b8e3d
Revises: None
Create Date: 2016-11-20 01:31:45.499432

"""

# revision identifiers, used by Alembic.
revision = 'f9ebfb0b8e3d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_created'), 'match', ['created'], unique=False)
    op.create_index(op.f('ix_match_status'), 'match', ['status'], unique=False)
    user_permission = op.create_table('user_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('avatar_medium', sa.String(), nullable=True),
    sa.Column('avatar_full', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('current_match', sa.Integer(), nullable=True),
    sa.Column('solo_mmr', sa.Integer(), nullable=True),
    sa.Column('vip_mmr', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_match'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=False)
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['user_permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('player_in_match',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('mmr_before', sa.Integer(), nullable=False),
    sa.Column('mmr_after', sa.Integer(), nullable=True),
    sa.Column('is_radiant', sa.Boolean(), nullable=False),
    sa.Column('is_leaver', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'match_id')
    )
    op.create_table('profile_scan_info',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('last_scan_request', sa.DateTime(), nullable=False),
    sa.Column('last_scan', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queued_player',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('queue_name', sa.String(length=20), nullable=False),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'queue_name')
    )
    op.create_index(op.f('ix_queued_player_added'), 'queued_player', ['added'], unique=False)
    op.create_table('user_mix_details',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_date', sa.DateTime(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('goal', sa.String(length=40), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mix_details_refresh_date'), 'user_mix_details', ['refresh_date'], unique=False)
    ### end Alembic commands ###


    ### Add permissions
    op.bulk_insert(user_permission,
                   [
                       {'name': 'admin'},
                       {'name': 'play_vip'}
                   ])
    ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mix_details_refresh_date'), table_name='user_mix_details')
    op.drop_table('user_mix_details')
    op.drop_index(op.f('ix_queued_player_added'), table_name='queued_player')
    op.drop_table('queued_player')
    op.drop_table('profile_scan_info')
    op.drop_table('player_in_match')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_table('user')
    op.drop_table('user_permission')
    op.drop_index(op.f('ix_match_status'), table_name='match')
    op.drop_index(op.f('ix_match_created'), table_name='match')
    op.drop_table('match')
    ### end Alembic commands ###
