PERMISSION_ADMIN = "admin"
PERMISSION_PLAY_VIP = "play_vip"
PERMISSION_VOUCH_VIP = "vouch_vip"

MATCH_STATUS_CREATION = 0
MATCH_STATUS_WAITING_FOR_PLAYERS = 1
MATCH_STATUS_CANCELLED = 2
MATCH_STATUS_IN_PROGRESS = 3
MATCH_STATUS_ENDED = 4
