PERMISSION_ADMIN = "admin"
PERMISSION_PLAY_VIP = "play_vip"
PERMISSION_VOUCH_VIP = "vouch_vip"

MATCH_STATUS_CREATION = 0
MATCH_STATUS_WAITING_FOR_PLAYERS = 1
MATCH_STATUS_CANCELLED = 2
MATCH_STATUS_IN_PROGRESS = 3
MATCH_STATUS_ENDED = 4

JOB_STEAM_STATUS_TODO = 0
JOB_STEAM_STATUS_SOLO_MMR_ACCEPTED = 1
JOB_STEAM_STATUS_SOLO_MMR_REFUSED = 2

BOT_JOB_PROCESS_PROFILE = 0

